/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f446re.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delayMillis(uint16_t delay);		//delay function

int main(void)
{
	//Clock activate for GPIOA AHB1ENR
	RCC->AHB1ENR |= 0x00000001U;

	GPIOA->MODER &= (0xA8000000U);
	GPIOA->MODER |= 0x00000001;
	GPIOA->PUPDR |= 0x00000010;

	while(1)
	{
		GPIOA->ODR |= 0x00000001 ;
		delayMillis(500);
		GPIOA->ODR &= 0x00000000;
		delayMillis(500);
	}
}

void delayMillis(uint16_t delay)
{
	uint16_t i = 0;
	for(;delay>0; --delay)
	{
		for(i = 0; i<1245;++i)
		{
			;
		}
	}
}
